<LandingPage>
    cols: 1
    Label:
        text: "Drag & Drop"
    Button:
        text: "Take Picture"
        on_press: root.camera_button()


<CameraPage>
    orientation: 'vertical'
    Camera:
        id: camera
        resolution: (640, 480)
        play: False
    #ToggleButton:
    #    text: 'Play'
    #    on_press: camera.play = not camera.play
    #    size_hint_y: None
    #    height: '48dp'
    Button:
        text: 'Back'
        size_hint_y: None
        height: '48dp'
        on_press: root.land()
    Button:
        text: 'Capture'
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()

<UploadPage>
    cols: 1
