# base python image
FROM python:3.5.7-alpine3.8

# set working directory
WORKDIR '/app'

RUN pip3 install flask && \
    pip3 install requests

COPY ./backend .
COPY ./models ./api/v1/models

CMD ["python3", "-m", "api.v1.app"]
